In [1]:
#Import Pandas
import pandas as pd

In [2]:
# Read Csv File
df=pd.read_csv("/kaggle/input/datasets/sp23bse071/studentperformance/student_performance.csv")

In [3]:
# Do one-hot encoding 
df = pd.get_dummies(df, columns=['Program'])

In [4]:
df.head(5)

,Student_ID,Name,Age,Python,Mathematics,Statistics,Machine_Learning,Attendance,Program_AI,Program_DS,Program_SE
0,S001,Ali Khan,20,85,78,92,88,95,True,False,False
1,S002,Sara Ahmed,21,72,75,70,80,90,True,False,False
2,S003,Ahmed Raza,22,90,88,91,93,96,False,False,True
3,S004,Fatima Noor,20,65,70,68,72,85,False,True,False
4,S005,Usman Ali,21,78,82,80,76,88,True,False,False

In [5]:
# Create New column of Average_Score
df['Average_Score']=(df['Python']+df['Mathematics']+df['Statistics']+df['Machine_Learning'])/4

In [6]:
df.head(5)

,Student_ID,Name,Age,Python,Mathematics,Statistics,Machine_Learning,Attendance,Program_AI,Program_DS,Program_SE,Average_Score
0,S001,Ali Khan,20,85,78,92,88,95,True,False,False,85.75
1,S002,Sara Ahmed,21,72,75,70,80,90,True,False,False,74.25
2,S003,Ahmed Raza,22,90,88,91,93,96,False,False,True,90.50
3,S004,Fatima Noor,20,65,70,68,72,85,False,True,False,68.75
4,S005,Usman Ali,21,78,82,80,76,88,True,False,False,79.00

In [7]:
# Select input and Output Features
X = df[['Python', 'Mathematics', 'Statistics', 'Machine_Learning']]
y = df['Average_Score']

In [8]:
# Split test and Train Data
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [9]:
# Print Shape of these
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(16, 4)
(4, 4)
(16,)
(4,)

In [10]:
# Perform Standarization
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)